//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 06:15:26 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://eSock.ro/ws/resources", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ro.esock.ws.resources;
